import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PedidoProvider } from "./ui/pedido/PedidoContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header style={{ background: "var(--primary)", color: "#fff" }} className="w-full flex items-center px-4 py-2 shadow-md sticky top-0 z-50">
      <Link href="/" className="flex items-center gap-2">
        <img
          src="/logo acai sem fundo.png"
          alt="Logo Açaí do Vale"
          style={{ width: 48, height: 48, objectFit: "contain", borderRadius: 12}}
        />
      </Link>
      <nav className="flex gap-4 ml-6">
        <Link href="/" className="hover:underline font-semibold">Início</Link>
        <Link href="/ui/pedido/tamanho" className="hover:underline font-semibold">Pedido</Link>
        <Link href="/ui/admin" className="hover:underline font-semibold">Admin</Link>
        <a href="mailto:contato@acai.com" className="hover:underline font-semibold">Contato</a>
      </nav>
    </header>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <PedidoProvider>
          <Header />
          {children}
        </PedidoProvider>
      </body>
    </html>
  );
}
