import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PedidoProvider } from "./ui/pedido/PedidoContext";
import Providers from "./providers";
import Link from "next/link";
import React from "react";
import HeaderClient from "./HeaderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return <HeaderClient />;
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>
          <PedidoProvider>
            <Header />
            {children}
          </PedidoProvider>
        </Providers>
      </body>
    </html>
  );
}
